### ISSUE TITLE
Paper online?

### ISSUE THREAD

**Issue by xialeiliu** [gjy3035/GCC-SFCN#1]
Is pdf of the paper available? I couldn't find it.

**Comment by gjy3035** [comment]
We are polishing our paper for camer ready. We will pre-print it in arxiv ASAP. If you want to use GCC dataset, you can download from [here](https://mailnwpueducn-my.sharepoint.com/:f:/g/personal/gjy3035_mail_nwpu_edu_cn/Eo4L82dALJFDvUdy8rBm6B0BuQk6n5akJaN1WUF1BAeKUA?e=ge2cRg) .

Thanks for you attention!

**Comment by xialeiliu** [comment]
Look forward to it! Thanks
