### ISSUE TITLE
Where Can I Find PreTrain model for "CrowdCounter" 

### ISSUE THREAD

**Issue by SJLNNU** [gjy3035/GCC-SFCN#12]
Hi ,
    I am using test.py with (torch 1.0 python 3.5.4 ),after i changed the model path to  downloaded "Pretrained_GCC.pth" .It seems this  pth's state_dict  mismatchs  CrowdCounter. Where Can I find the right pretrain pth for CrowdCounter? or Did i miss things?Please let me know.

**Comment by SJLNNU** [comment]
Weird  things happened  is that Everything shared in this Link[https://mailnwpueducn-my.sharepoint.com/personal/gjy3035_mail_nwpu_edu_cn/Documents/Forms/All.aspx?cid=63b26663-010c-4bc9-82da-7b6bd82d83a4&RootFolder=%2Fpersonal%2Fgjy3035_mail_nwpu_edu_cn%2FDocuments%2F%E8%AE%BA%E6%96%87%E5%BC%80%E6%BA%90%E6%95%B0%E6%8D%AE%2FGCC-SFCN&FolderCTID=0x012000B11760F9CD00774384C33CD380EA40D3](url) is Broken . Would you please share the model to my Email? NJNUSJL@gmail.com 
Thank you for your time .

**Comment by Yellow-Champagne** [comment]
[https://github.com/pytorch/vision/tree/master/torchvision/models](url)

**Comment by SJLNNU** [comment]
@Yellow-Champagne  Hi ,Sorry for  the misunderstanding . The PreTrain model i mean is not the 'resnet101-5d3b4d8f.pth' loaded in resSFCN.py . But the  model loaded in test.py Line 36 . 
And I write a test code to test 'Pretrained_GCC.pth' I downloaded form the Link in README -[Data preparation] .
——————————————————————————————

model_path='Pretrained_GCC.pth'
net = CrowdCounter()
net.load_state_dict(torch.load(model_path))
_________________________________________________________________________
And it goes mismatch . I cant open any file i downloaded from the Link,So it must be file problem .If you have the right file please Email me .
Thank you for your time .

**Comment by gjy3035** [comment]
1. I check the link of Pretrained_GCC.pth, and it is ok. I think you may need VPN to visit it.
2. About mismatching problem, please post the details error information. You would see https://github.com/gjy3035/GCC-SFCN/issues/8.

**Comment by SJLNNU** [comment]
Thanks , I have succeeded.  The Same problem in #8 .I am closing it .
