### ISSUE TITLE
Idea: combine supervised and domain adaptation methods

### ISSUE THREAD

**Issue by PetitBai** [gjy3035/GCC-SFCN#17]
Hi, Junyu, have you tried to pre-train the **supervised SFCN model** using **translated GCC datasets via SE Cycle GAN** and then, fine-tune the model with real images? This may work well,  i think.

**Comment by PetitBai** [comment]
@gjy3035

**Comment by gjy3035** [comment]
About this exp, I plan to do it in our extension version. Unfortunately, we now have no time to focus on this work. 
Your idea is very interesting and you can have a try. I am looking forward to your results!

**Comment by gjy3035** [comment]
@PetitBai Could you provide your email or account of WeChat/QQ? We can discuss it deeply. Thanks a lot! My email is gjy3035@gmail.com.

**Comment by PetitBai** [comment]
@gjy3035 :) ,my wechat - baishuo199x
