### ISSUE TITLE
The pretrained model is not in accordance with resSFCN

### ISSUE THREAD

**Issue by Ethanwl** [gjy3035/GCC-SFCN#4]
The len of pretrained model's state_dict is 488 and that of resSFCN is 582.
If I want to finetune the model, what the details should I notice? For example, in shanghaiB, how to preprocess images and how to set optimizer?

**Comment by gjy3035** [comment]
1. some layers in resSFCN do not the learnable parameters, such as ReLU, Pooling, etc. so the length of save weights is not same as that of the graph in the code.
2. you could directly run our code, which will work well.
`__C.TRAIN.PRE_GCC_MODEL = './pre/Pretrained_GCC.pth'`: finetune the model using GCC pretrained model
`__C.TRAIN.PRE_GCC_MODEL = ''`:  finetune the model using ImgNt pretrained model
3. for shanghai b, we will release the code in C^3 Framework. We will only focus on the implementation on the new framework. 
If you want to finetune the model on shanghai B, you should replace the hyper parameters as follows:
`__C.DATA.MEAN_STD ` and `__C.DATA.DATA_PATH`.

Other parameters should fixed.
